---
downloads: ~/.ansible-downloads/

configure_dotfiles: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Contacts
  - Calendar
  - Notes
  - Reminders
  - Maps
  - Photos
  - Pages
  - Numbers
  - Keynote
  - Books
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 2
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app"
  - name: "TablePlus"
    path: "/Applications/TablePlus.app"
  - name: "Keka"
    path: "/Applications/Keka.app"

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/caycehouse/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .ssh/config
  - .gitconfig
  - .gitignore
  - .p10k.zsh
  - .vimrc
  - .zprofile
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bat
  - blueutil
  - diff-so-fancy
  - dos2unix
  - eza
  - gh
  - git
  - htop
  - ipcalc
  - iperf3
  - jq
  - python@3.10
  - neofetch
  - nmap
  - node
  - zstd
  - openjdk
  - prettier
  - prettyping
  - python@3.9
  - rclone
  - restic
  - shellcheck
  - ssh-copy-id
  - swiftlint
  - tealdeer
  - telnet
  - tmux
  - topgrade
  - wget
  - yamllint
  - yarn
  - yq

homebrew_taps:
  - {name: "caycehouse/personal", url: "https://github.com/caycehouse/homebrew-personal.git"}
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - 1password-cli
  - adobe-acrobat-reader
  - airpods-sound-quality-fixer
  - altserver
  - appcleaner
  - balenaetcher
  - curseforge
  - cyberduck
  - dash
  - devtoys
  - discord
  - docker
  - epic-games
  - feed-the-beast
  - font-fira-code
  - github
  - gog-galaxy
  - graphql-playground
  - iterm2
  - keka
  - kekaexternalhelper
  - kindle
  - microsoft-auto-update
  - microsoft-teams
  - moonlight
  - obsidian
  - onyx
  - openrct2
  - openscad
  - origin
  - parsec
  - postman
  - prismlauncher
  - profilecreator
  - rectangle
  - runelite
  - sidequest
  - silentknight
  - slack
  - steam
  - superslicer
  - suspicious-package
  - tableplus
  - ultimaker-cura
  - visual-studio-code
  - vlc
  - vmware-fusion
  - webex
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 1569813296, name: "1Password for Safari"}
  - {id: 1037126344, name: "Apple Configurator"}
  - {id: 1019371109, name: "Balance Lock"}
  - {id: 1287239339, name: "ColorSlurp"}
  - {id: 640199958, name: "Developer"}
  - {id: 1381004916, name: "Discovery"}
  - {id: 1444383602, name: "GoodNotes"}
  - {id: 1474276998, name: "HP Smart"}
  - {id: 409183694, name: "Keynote"}
  - {id: 462058435, name: "Microsoft Excel"}
  - {id: 784801555, name: "Microsoft OneNote"}
  - {id: 985367838, name: "Microsoft Outlook"}
  - {id: 462062816, name: "Microsoft PowerPoint"}
  - {id: 1295203466, name: "Microsoft Remote Desktop"}
  - {id: 462054704, name: "Microsoft Word"}
  - {id: 409203825, name: "Numbers"}
  - {id: 823766827, name: "OneDrive"}
  - {id: 409201541, name: "Pages"}
  - {id: 409907375, name: "Remote Desktop"}
  - {id: 1246969117, name: "Steam Link"}
  - {id: 1475387142, name: "Tailscale"}
  - {id: 1176074088, name: "Termius"}
  - {id: 1320666476, name: "Wipr"}
  - {id: 497799835, name: "Xcode"}
mas_email: ""
mas_password: ""

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Path to oh-my-zsh custom directory.
zsh_custom: "~/.oh-my-zsh/custom"

# List of oh-my-zsh plugins.
zsh_plugins:
  - repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_custom }}/themes/powerlevel10k"
  - repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
  - repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ zsh_custom }}/plugins/zsh-completions"
  - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"
  - repo: https://github.com/z-shell/zsh-eza.git
    dest: "{{ zsh_custom }}/plugins/zsh-eza"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
