---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml
    - vars/fedora.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
      when: ansible_distribution == 'MacOSX'
    - role: geerlingguy.mac.homebrew
      when: ansible_distribution == 'MacOSX'
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: (mas_installed_apps or mas_installed_app_ids) and ansible_distribution == 'MacOSX'
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock and ansible_distribution == 'MacOSX'
      tags: ['dock']
    - role: petermosmans.customize-gnome
      when: ansible_distribution == 'Fedora'
      tags: ['gnome']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/fedora.yml
      when: ansible_distribution == 'Fedora'
      tags: ['fedora']

    - import_tasks: tasks/zsh.yml
      tags: ['zsh']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run post-provision task files in a block.
      tags: ['post']
      block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks | default(omit) }}"
