---
- name: Perform dnf installation.
  block:
    # Repository.
    - name: Ensure configured repositories are enabled.
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.url }}"
      loop: "{{ yum_repositories }}"

    # dnf.
    - name: Ensure configured dnf packages are installed.
      ansible.builtin.dnf:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ dnf_installed_packages }}"
  become: true
