---
- name: Perform dnf installation.
  become: true
  block:
    # Repository.
    - name: Ensure configured repositories are enabled.
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.url }}"
        file: "{{ item.file | default(item.name) }}"
        gpgcheck: "{{ item.gpgcheck | default(false) }}"
        repo_gpgcheck: "{{ item.repo_gpgcheck | default(false) }}"
        gpgkey: "{{ item.gpgkey | default() }}"
      loop: "{{ yum_repositories }}"

    # dnf.
    - name: Ensure configured dnf packages are installed.
      ansible.builtin.dnf:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ dnf_installed_packages }}"

    # flatpak.
    - name: Ensure configured flatpaks are installed.
      community.general.flatpak:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      loop: "{{ flatpak_installed_packages }}"
